### ISSUE TITLE
Price is not modified after updating quantity on credit memo

### ISSUE THREAD

**Issue by Viinz** [mageprince/magento2-extrafee#31]
Hi,

I have your module installed on one of my project.
For each item we have 15$ extra fee called "Service prioritaire".

If I create a credit memo on the order the price is right.
But if I update the item quantity the price does not change.

**Before update :**
![image](https://user-images.githubusercontent.com/3815871/96306767-4fb6ed00-0fce-11eb-9bfc-b17519537d8d.png)

**After update :**
![image](https://user-images.githubusercontent.com/3815871/96306851-7ffe8b80-0fce-11eb-86f5-b594232d28c5.png)

My current module version is 2.4.
Have you a fix for this ?

Thank you !

**Comment by mageprince** [comment]
Hi @Viinz Thanks for posting an issue.
It is not calculated dynamically on credit memo, because extra fee is added to order totals based on extra fee condition at the time of order placement. For a refund, it is working the same as refund shipping. As you can see your screenshot shipping also not changes dynamically. You have an option to change the extra fee manually on credit memos.
